[project]
name = 'Verified-Carbon-Offset-Exchange'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.automated-credit-issuance]
path = 'contracts/automated-credit-issuance.clar'
clarity_version = 3
epoch = '3.2'

[contracts.carbon-project-registry]
path = 'contracts/carbon-project-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.corporate-offset-compliance]
path = 'contracts/corporate-offset-compliance.clar'
clarity_version = 3
epoch = '3.2'

[contracts.individual-carbon-wallet]
path = 'contracts/individual-carbon-wallet.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
